### ISSUE TITLE
🚧  Switch to Talos + Sidero 🔥 

### ISSUE THREAD

**Issue by ahinko** [ahinko/home-ops#26]
Currently running Ubuntu + k3s but I want to switch to [Talos](www.talos.dev) + [Sidero](www.sidero.dev)

## Hardware
- Sidero on a Raspberry Pi 4 with an SSD.
- Workload cluster with 4 Intel NUC:s

## Todo
- [x] Finish evaluating and testing
- [x] Finalize scripts to provision Sidero and Metal/workload cluster
- [ ] Rebuild the metal/workload cluster with all nodes
- [ ] Enable all services (one at the time) and make sure everything works.

### Question marks / research needed
See further down in the issue for more information on each topic
- [x] Storage, Rook Ceph is the choice, 
  - Mayastor seems really interesting but it need's more time. Backups are an issue and I also found a report that someone had issues running Postgres.
- [x] Backup, keep using `simple-k8s-backup` for now

### Things to test
- [x] 🚧 DOCUMENT EVERY STEP!
- [x] 🚧 Create `tasks` + `bash scripts` for as much as possible or automate in other ways.
- [x] Move cluster to own VLAN (25)
  - [x] Move Sidero RPi to new VLAN
  - [x] Set up a DHCP server on the RPi running Sidero
    - [x] Setup iPXE boot
  - [x] Move Helios to new VLAN
- [x] Prepare the Raspberry Pi 4 and install Talos + Sidero
  - [x] Make the Pi:s boot from SSD.
  - [x] Write Talos to the SSDs.
  - [x] Install Sidero
- [x] Prepare resource manifests
  - [x] environments
  - [x] clusters
  - [x] serverclasses
  - [x] servers
- [x] Remove `helios` from old cluster, `kubectl drain helios --ignore-daemonsets --delete-local-data` and `kubectl delete node helios`
  - [x] Also from rook-ceph cluster
  - [x] Make sure Helios has one of the Coral USB attached so we can test that it works with Talos
- [x] Restructure git repository to match new architecture
  - [x] Use a separate folder for the new cluster so we can have old and new cluster run in parallel
  - [x] ~~Remove namespace definitions in `cluster/core/namespaces`.~~
  - [x] Use [Cilium](https://cilium.io/)
    - Look at https://www.talos.dev/docs/v0.14/guides/deploying-cilium/#machine-config-preparation
    - [x] Would be nice to handle updates using regular way (renovate + flux) but would also be good to deploy CNI before Flux
    - [x] https://raw.githubusercontent.com/ahinko/homelab/main/clusters/integrations/cilium-quick-install/quick-install.yaml Will not work since its a private repo
- [x] Add Flux to the new cluster
  - [x] Add basic stuff like `node-feature-discovery` etc.
- [x] Add Helios to `metal` cluster
  - [x] Verify Coral USB
  - [x] Verify Intel Quick Sync
  - [x] ~~Wipe `/dev/sda` with `simple-ceph-zap` (rename)~~ 
    - [x] Seems like Sidero/Talos wipes the drive for us when the node is accepted. Verify that they wipe it enough.
    - [x] or maybe use this: https://github.com/Truxnell/home-cluster/blob/main/tools/wipe-rook.yaml

## Fixes and improvements to do
- [x] Set dns/nameservers for Sidero RPi
- [x] Set hostname on Sidero RPi
- [x] Hostname is not correctly set on metal machines 
- [x] Test merge #961 and see if Sidero does what it is supposed to do (automatically update the nodes)
- [x] DHCPD does not start since we have the `cmd` specified in the deployment. Needs to be fixed
  - Inspiration: https://github.com/networkboot/docker-dhcpd
- [x] Remove metal cluster
- [x] Wipe Sidero
- [x] Write a `bash` script instead of `taskfile` for bootstrapping Sidero
  - Inspiration: https://github.com/rgl/sidero-vagrant/blob/main/provision-sidero.sh
  - [x] Test it!
- [x] Write a `bash` script instead of `taskfile` for bootstrapping Metal cluster.
  - [x] Test it!
