### ISSUE TITLE
⛵ Automatically update which version of Kubernetes Renovate can update to

### ISSUE THREAD

**Issue by ahinko** [ahinko/home-ops#8]
## What's the problem?
I've had issues where the Kubernetes version I specified in the metal cluster config did not work with the current Talos version.

## Suggested solution
In [allowedVersions.json5](https://github.com/ahinko/home-ops/blob/main/.github/renovate/allowedVersions.json5) we specify which version of Kubernetes Renovate can update to. The missing piece is to automatically update the [allowedVersions.json5](https://github.com/ahinko/home-ops/blob/main/.github/renovate/allowedVersions.json5) automatically when Talos ships with a new minor version. Patch versions can be updated even if Talos does ship with an older version.

## Todo:
- [x] Add spec to [allowedVersions.json5](https://github.com/ahinko/home-ops/blob/main/.github/renovate/allowedVersions.json5). Only update kubernetes version when Talos is on the same version. IE only update patch versions.
- [ ] Github action that updates [allowedVersions.json5](https://github.com/ahinko/home-ops/blob/main/.github/renovate/allowedVersions.json5) when Talos updates to new minor release 1.x.
  - [ ] Run action only when PR and specific file is updated (one of the files with Talos version)
  - [x] Check if Talos version changed
  - [x] ~~Check dependency, Talos release notes includes updated images.~~ Better if we can find current version instead since k8s images isnt always updated
