### ISSUE TITLE
Switch registrar for private domain

### ISSUE THREAD

**Issue by ahinko** [ahinko/home-ops#91]
## Todo
- [ ] Move DNS to Cloudflare
  - [ ] Make sure all settings are copied
  - [ ] E-mail provider has a tool for making sure all DNS settings are set correctly. USE IT!
- [ ] Switch to the new registrar we use for other domains
